Inspinia_MVC5_SeedProject/Controllers/BasesController.cs
using EFCore;
using EFData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TFG.Contrato;

namespace Inspinia_MVC5_SeedProject.Controllers
{
    public class BasesController : Controller
    {
        private IRepositoryBases repository = new BaseMap();

        // GET: Bases
        public ActionResult Index()
        {
            ViewData["SubTitle"] = "Aplicacion para el Control de Combustible en Flotas de Vehículos";
            ViewData["Message"] = "Estas en BASES";
            List<Base> bases = repository.GetAllBases();
            return View(bases);
        }

        public ActionResult Editar(int id)
        {
            Base b = new Base();
            b = repository.GetBase(id);

            if (b == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(b);
        }

        [HttpPost]
        public ActionResult Editar(int id, [Bind(Include = "Descripcion, Latitud, Longitud")] Base _base)
        {
            Base b = new Base();
            b = repository.GetBase(id);
            b.Descripcion = _base.Descripcion;
            b.Latitud = _base.Latitud;
            b.Longitud = _base.Longitud;
            repository.GuardarDatos();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Insertar()
        {
            var _base = new Base();
            return View(_base);
        }

        [HttpPost]
        public ActionResult Insertar(Base _base)
        {
            repository.InsertarBase(_base);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            Base b = new Base();
            b = repository.GetBase(id);

            if (b == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(b);
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult DeleteConfirmed(int id)
        {
            Base b= new Base();
            b = repository.GetBase(id);
            repository.DeleteBase(b);
            return RedirectToAction("Index");
        }
    }
}

Inspinia_MVC5_SeedProject/Controllers/TransaccionesController.cs
using EFCore;
using System.Collections.Generic;
using System.Web.Mvc;
using TFG.Contrato;
using EFData;

namespace Inspinia_MVC5_SeedProject.Controllers
{
    public class TransaccionesController : Controller
    {
        private IRepositoryTransacciones repository = new TransaccionMap();

        // GET: Transacciones
        public ActionResult Index()
        {
            ViewData["SubTitle"] = "Aplicacion para el Control de Combustible en Flotas de Vehículos";
            ViewData["Message"] = "Estas en TRANSACCIONES";
            List<Transaccion> transacciones = repository.GetAllTransacciones();
            return View(transacciones);
        }

        [HttpGet]
        public ActionResult Insertar()
        {
            var transaccion = new Transaccion();
            return View(transaccion);
        }

        [HttpPost]
        public ActionResult Insertar(Transaccion transaccion)
        {
            repository.InsertarTransaccion(transaccion);

            return RedirectToAction("Index");
        }
    }
}

Inspinia_MVC5_SeedProject/Controllers/UsuariosController.cs
using EFCore;
using EFData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TFG.Contrato;

namespace Inspinia_MVC5_SeedProject.Controllers
{
    public class UsuariosController : Controller
    {
        private IRepositoryUsuarios usuarioRepository = new UsuarioMap();
        

        // GET: Usuarios
        public ActionResult Index()
        {
            ViewData["SubTitle"] = "Aplicacion para el Control de Combustible en Flotas de Vehículos";
            ViewData["Message"] = String.Format("Estas en USUARIOS");
            List<Usuario> usuarios = usuarioRepository.GetAllUsers();            
            return View(usuarios.ToList());
        }

        //GET: /Usuario/Detail/5
        public ActionResult Editar(int id)
        {
            Usuario u = new Usuario();
            u = usuarioRepository.GetUser(id);

            if (u == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(u);

        }
        
        [HttpPost] 
        public ActionResult Editar(int id, [Bind(Include ="Nombre, User, Password")] Usuario usuario)
        {
            Usuario u = new Usuario();
            u = usuarioRepository.GetUser(id);
            u.Nombre = usuario.Nombre;
            u.Password = usuario.Password;
            u.User = usuario.User;
            usuarioRepository.GuardarDatos();
            return RedirectToAction("Index");
        }  

        [HttpGet]
        public ActionResult Insertar()
        {
            var usuario = new Usuario();
            return View(usuario);
        }

        [HttpPost]
        public ActionResult Insertar(Usuario usuario)
        {
            usuarioRepository.InsertUser(usuario);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            Usuario u = new Usuario();
            u = usuarioRepository.GetUser(id);

            if (u == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(u);           
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario u = new Usuario();
            u = usuarioRepository.GetUser(id);
            usuarioRepository.DeleteUser(u);
            return RedirectToAction("Index");
        }
    }
}

Inspinia_MVC5_SeedProject/Controllers/VehiculosController.cs
using EFCore;
using EFData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TFG.Contrato;

namespace Inspinia_MVC5_SeedProject.Controllers
{
    public class VehiculosController : Controller
    {
        private IRepositoryVehiculos repository = new VehiculoMap();

        // GET: Vehiculos
        public ActionResult Index()
        {
            ViewData["SubTitle"] = "Aplicacion para el Control de Combustible en Flotas de Vehículos";
            ViewData["Message"] = "Estas en VEHICULOS";
            List<Vehiculo> vehiculos = repository.GetAllVehiculos();
            return View(vehiculos);
        }

        public ActionResult Editar(int id)
        {
            Vehiculo v = new Vehiculo();
            v = repository.GetVehiculo(id);

            if (v == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(v);

        }

        [HttpPost]
        public ActionResult Editar(int id, [Bind(Include = "Matricula, Marca, Modelo")] Vehiculo vehiculo)
        {
            Vehiculo v = new Vehiculo();
            v = repository.GetVehiculo(id);
            v.Marca = vehiculo.Marca;
            v.Modelo = vehiculo.Modelo;
            v.Matricula = vehiculo.Matricula;
            repository.GuardarDatos();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Insertar()
        {
            var vehiculo = new Vehiculo();
            return View(vehiculo);
        }

        [HttpPost]
        public ActionResult Insertar(Vehiculo vehiculo)
        {
            repository.InsertarVehiculo(vehiculo);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            Vehiculo v = new Vehiculo();
            v = repository.GetVehiculo(id);

            if (v == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(v);
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehiculo v = new Vehiculo();
            v = repository.GetVehiculo(id);
            repository.DeleteVehiculo(v);
            return RedirectToAction("Index");
        }

    }
}

Inspinia_MVC5_SeedProject/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Desarrollado por: Gabriel Julián
    </div>
    <div>
        &copy; 2016 <strong>Trabajo Fin de Grado: </strong> Sistema de Control de Combustible en Flotas.
    </div>
</div>

Inspinia_MVC5_SeedProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TFG | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/metsiMenu")
    @Scripts.Render("~/plugins/pace")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @RenderSection("scripts", required: false)
</body>
</html>

Inspinia_MVC5_SeedProject/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Gabriel</strong>
                            </span> <span class="text-muted text-xs block">Perfil <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">Cerrar Sesión</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    GJC
                </div>
            </li>
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-laptop"></i> <span class="nav-label">Dashboard</span> </a>
            </li>
            @*<li class="@Html.IsSelected(action: "Minor")">
                <a href="@Url.Action("Minor", "Home")"><i class="fa fa-desktop"></i> <span class="nav-label">Minor page</span></a>
            </li>*@
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Usuarios")"><i class="fa fa-laptop"></i> <span class="nav-label">Usuarios</span> </a>
            </li>
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Bases")"><i class="fa fa-laptop"></i> <span class="nav-label">Bases</span> </a>
            </li>
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Vehiculos")"><i class="fa fa-laptop"></i> <span class="nav-label">Vehículos</span> </a>
            </li>
            <li class="@Html.IsSelected(action: "Index")">
                <a href="@Url.Action("Index", "Transacciones")"><i class="fa fa-laptop"></i> <span class="nav-label">Transacciones</span> </a>
            </li>
        </ul>
    </div>
</nav>

Inspinia_MVC5_SeedProject/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="@Url.Action("Index", "Home")" ></a>
            <form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">
                    <input type="text" placeholder="Buscar..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
        @Html.Partial("_LoginPartial")
    </nav>
</div>